[phases.setup]
nixPkgs = ['nodejs', 'npm', 'python3', 'gcc', 'gnumake']

[phases.install]
cmd = 'cd server && npm ci'

[phases.build]
cmd = 'cd server && npm run build:prod'

[start]
cmd = 'cd server && npm run start:prod'